CREATE TABLE USERS
(
    USER_ID      BIGSERIAL PRIMARY KEY,
    FIRST_NAME   VARCHAR(100) NOT NULL,
    LAST_NAME    VARCHAR(100) NULL,
    GENDER       VARCHAR(20)  NOT NULL,
    EMAIL        VARCHAR(200) NOT NULL UNIQUE,
    USERNAME     VARCHAR(10)  NOT NULL UNIQUE,
    PHONE        VARCHAR(10)  NULL,
    PHONE_CODE   VARCHAR(10)  NULL,
    PASSWORD     VARCHAR(500) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USERS(FIRST_NAME, LAST_NAME, GENDER, EMAIL, USERNAME, PHONE, PHONE_CODE, PASSWORD)
VALUES ('Pradum', 'Kumar', 'Male', 'pradumraj98@gmail.com', 'pradum98', '123456789', '91', '12345');



CREATE TABLE TRAIN
(
    TR_NO    NUMERIC(10) PRIMARY KEY,
    TR_NAME  VARCHAR(70)   NOT NULL,
    FROM_STN VARCHAR(20)   NOT NULL,
    TO_STN   VARCHAR(20)   NOT NULL,
    SEATS    NUMERIC(4)    NOT NULL,
    FARE     NUMERIC(6, 2) NOT NULL
);



INSERT INTO TRAIN
VALUES (10001, 'JODHPUR EXP', 'HOWRAH', 'JODHPUR', 152, 490.50)
        ,
       (10002, 'YAMUNA EXP', 'GAYA', 'DELHI', 52, 550.50)
        ,
       (10003, 'NILANCHAL EXP', 'GAYA', 'HOWRAH', 92, 451)
        ,
       (10004, 'JAN SATABDI EXP', 'RANCHI', 'PATNA', 182, 550),
       (10005, 'GANGE EXP', 'MUMBAI', 'KERALA', 12, 945),
       (10006, 'GARIB RATH EXP', 'PATNA', 'DELHI', 1, 1660.75),
       (10007, 'PATIPUTRA', 'KIUL', 'HATIA', 16, 1450.75),
       (10008, 'VIKRAMSILA', 'BHAGALPUR', 'PATNA', 61, 1660.75);


CREATE TABLE HISTORY
(
    HISTORY_ID SERIAL PRIMARY KEY,
    PASSENGER_NAME   VARCHAR(40),
    PASSENGER_PHONE   VARCHAR(40),
    PASSENGER_AGE   VARCHAR(40),
    JOURNEY_DATE varchar(20),
    TRAIN_NO    NUMERIC(10),
    FROM_STN VARCHAR(20)   NOT NULL,
    TO_STN   VARCHAR(20)   NOT NULL,
    STATUS VARCHAR(20),
    Reservation_BY INT,
    SEATS_NUM    NUMERIC(3)    NOT NULL,
    PNR_NUMBER NUMERIC(50),
    AMOUNT   NUMERIC(8, 2) NOT NULL
);


